service: webhook-test

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

  httpApi:
    cors: true
    authorizers:
      Auth0:
        identitySource: $request.header.Authorization
        issuerUrl: https://login.tanverhasan.com/
        audience:
          - https://test.webhook.com

functions:
  httpGet:
    handler: src/lambda/httpGet.httpGet
    events:
      - httpApi:
          method: GET
          path: /hook
  #          authorizer: Auth0
  sendPost:
    handler: src/lambda/httpPost.sendPost
    events:
      - httpApi:
          method: POST
          path: /hook
  #          authorizer: Auth0

  delay:
    handler: src/lambda/delay.delayEndpoint
    events:
      - httpApi:
          method: GET
          path: /hook/{timer}
  #         authorizer: Auth0
