service: webhook-test

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

  httpApi:
    cors: true
    authorizers:
      Auth0:
        identitySource: $request.header.Authorization
        issuerUrl: https://login.tanverhasan.com/
        audience:
          - https://test.webhook.com

functions:
  sendPost:
    handler: src/lambda/handler.sendPost
    events:
      - httpApi:
          method: POST
          path: /hook
#          authorizer: Auth0

  delay:
    handler: src/lambda/handler.delayEndpoint
    events:
      - httpApi:
          method: GET
          path: /hook/{timer}
  #         authorizer: Auth0
